global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']
- job_name: 'speedtester'
  scrape_interval: 5m
  scrape_timeout: 10s
  static_configs:
  - targets: ['speedtester:8080']
