{
 "title": "Home Internet",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(speedtest_download_speed{}, server_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_download_speed{server_name=\"$server\"})",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_upload_speed{server_name=\"$server\"})",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Download Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_download_latency{server_name=\"$server\",latency=\"iqm\"})",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Upload Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_upload_latency{server_name=\"$server\",latency=\"iqm\"})",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_ping_latency{server_name=\"$server\",latency=\"iqm\"})",
     "legendFormat": "Ping"
    }
   ]
  },
  {
   "title": "Packt Loss",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_packet_loss{server_name=\"$server\"})",
     "legendFormat": "Ping"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum(speedtest_download_speed{server_name=\"$server\"})",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(speedtest_upload_speed{server_name=\"$server\"})",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Download Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(speedtest_download_latency{server_name=\"$server\"}) by (latency)",
     "legendFormat": "{{latency}}"
    }
   ]
  },
  {
   "title": "Upload Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(speedtest_upload_latency{server_name=\"$server\"}) by (latency)",
     "legendFormat": "{{latency}}"
    }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(speedtest_ping_latency{server_name=\"$server\"}) by (latency)",
     "legendFormat": "{{latency}}"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(speedtest_download_jitter{server_name=\"$server\"})",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(speedtest_upload_jitter{server_name=\"$server\"})",
     "legendFormat": "Upload"
    },
    {
     "expr": "sum(speedtest_ping_jitter{server_name=\"$server\"})",
     "legendFormat": "Ping"
    }
   ]
  }
 ]
}